import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {BASE,record,e,markdown,github,reportHref} from './render.mjs';
const ROOT=path.resolve(import.meta.dirname,'..');
const OUT=path.join(ROOT,'_site');
const metadata=fs.existsSync(path.join(ROOT,'metadata.json'))?JSON.parse(fs.readFileSync(path.join(ROOT,'metadata.json'),'utf8')):{};
const records=[];
for(const dir of fs.readdirSync(ROOT,{withFileTypes:true})){
  if(!dir.isDirectory()||!/^\d{4}-\d{2}-\d{2}$/.test(dir.name))continue;
  for(const name of fs.readdirSync(path.join(ROOT,dir.name))){
    if(!/^\d{2}-\d{2}-\d{2}(?:-【[^】/]+】-[^/]+|_[^/]+)\.md$/.test(name))continue;
    const p=dir.name+'/'+name, md=fs.readFileSync(path.join(ROOT,p),'utf8');
    const b=Buffer.from(md);const sha=crypto.createHash('sha1').update(Buffer.concat([Buffer.from(`blob ${b.length}\0`),b])).digest('hex');
    records.push(record({...metadata[p],path:p,sha,markdown:md}));
  }
}
records.sort((a,b)=>b.path.localeCompare(a.path));
if(!records.length)throw new Error('No dated research Markdown found');
const dates=[...new Set(records.map(r=>r.date))];
const themes=[...new Set(records.flatMap(r=>[r.type,...r.tags]))].sort((a,b)=>a.localeCompare(b,'zh'));
const types=[...new Set(records.map(r=>r.type))];
const homepage=BASE;
function badges(r){return '<span class="topic">'+e(r.type)+'</span>'+r.tags.filter(t=>t!==r.type).map(t=>'<span class="tag">'+e(t)+'</span>').join('');}
function layout(title,body,script=false){return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="X-feed 公开研究记录。按时间和主题浏览研究结论、原始来源与风险边界。"><meta name="theme-color" content="#11283b"><meta name="referrer" content="strict-origin-when-cross-origin"><title>${e(title)} · X-feed</title><link rel="icon" href="${BASE}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${BASE}assets/style.css">${script?`<script defer src="${BASE}assets/filters.js"></script>`:''}</head><body><a class="skip" href="#main">跳转到正文</a><header><div class="top"><a class="brand" href="${homepage}">X-feed<span>研究记录</span></a><a class="public-label" href="https://github.com/Sakkana/X-feed-pages">公开归档 ↗</a></div></header><div class="workspace"><aside class="sidebar" aria-label="研究记录导航"><p class="nav-label">研究归档</p><ul class="nav-list"><li><a href="${homepage}">全部记录 <span class="count">${records.length}</span></a></li></ul><div class="sidebar-block"><p class="nav-label">按日期浏览 · 北京时间</p><ul class="nav-list">${dates.map(d=>`<li><a href="${homepage}?date=${d}">${d}<span class="count">${records.filter(r=>r.date===d).length}</span></a></li>`).join('')}</ul></div><div class="sidebar-block"><p class="nav-label">主要主题</p><ul class="nav-list">${types.map(t=>`<li><a href="${homepage}?type=${encodeURIComponent(t)}">${e(t)}<span class="count">${records.filter(r=>r.type===t||r.tags.includes(t)).length}</span></a></li>`).join('')}</ul></div><div class="side-note">保留当时的来源、判断与风险。<br>最新研究位于最上方。<a href="https://github.com/Sakkana/X-feed-pages">GitHub 原始归档 ↗</a></div></aside><main class="main" id="main">${body}</main></div><footer class="foot"><span>研究记录不构成投资建议；历史收益、报价与判断不代表当前情况。</span><a href="${BASE}reports.json">机器可读索引</a></footer></body></html>`;}
let body=`<div class="page-heading"><div><p class="eyebrow">Research archive</p><h1>研究时间线</h1><p class="page-meta">按报告时间倒序 · 北京时间 UTC+08:00</p></div><div class="total"><strong id="result-count">${records.length}</strong>篇记录</div></div><p class="intro">从线索到证据，记录每一次判断。按时间回看研究，按主题追踪变化。</p><form class="filters" role="search"><label>研究日期<select id="date-filter" name="date"><option value="">全部日期</option>${dates.map(d=>`<option value="${d}">${d}</option>`).join('')}</select></label><label>主题 / 标签<select id="type-filter" name="type"><option value="">全部主题</option>${themes.map(t=>`<option value="${e(t)}">${e(t)}</option>`).join('')}</select></label><label>搜索标题 / 摘要<input id="query-filter" name="q" type="search" placeholder="例如 Pendle、风险" autocomplete="off"></label><button type="reset">清除筛选</button></form><nav class="filter-topics" aria-label="快捷主题筛选"><a href="${BASE}" data-theme="">全部</a>${['DeFi','DEX','套利','山寨币估值','RWA','账号增长'].filter(t=>themes.includes(t)).map(t=>`<a data-theme="${e(t)}" href="${BASE}?type=${encodeURIComponent(t)}">${e(t)}</a>`).join('')}</nav><p id="filter-status" class="page-meta" role="status" aria-live="polite"></p><noscript><p class="caution">当前显示全部记录。主题、日期及关键词筛选需要启用 JavaScript；阅读全文无需 JavaScript。</p></noscript><div id="empty-state" class="empty" hidden>这个范围内没有研究记录<br><a href="${BASE}">查看全部记录</a></div>`;
for(const d of dates){const group=records.filter(r=>r.date===d);body+=`<section data-day="${d}" aria-label="${d} 的报告"><div class="date-row"><h2>${d}</h2><div class="line"></div><span class="day-count">${group.length} 篇</span></div>`;for(const r of group){body+=`<div class="entry" data-path="${e(r.path)}" data-date="${r.date}" data-themes="${e(JSON.stringify([r.type,...r.tags]))}" data-search="${e([r.title,r.summary,r.type,...r.tags].join(' ').toLowerCase())}"><div class="stamp"><time datetime="${r.date}T${r.time}+08:00">${r.time}</time></div><a class="report-card" href="${reportHref(r.path)}"><div class="card-top">${badges(r)}${r===records[0]?'<span class="latest">最新记录</span>':''}</div><h3 class="card-title">${e(r.title)}</h3><p class="summary">${e(r.summary)}</p><div class="card-bottom"><span>核验 ${e(r.observation)}</span><span class="read-label">阅读全文 →</span></div></a></div>`;}body+='</section>';}
fs.rmSync(OUT,{recursive:true,force:true});fs.mkdirSync(OUT,{recursive:true});fs.cpSync(path.join(ROOT,'assets'),path.join(OUT,'assets'),{recursive:true});
fs.writeFileSync(path.join(OUT,'index.html'),layout('研究时间线',body,true));
for(const [idx,r] of records.entries()){
  const content=`<a class="back" href="${BASE}?date=${r.date}">← 返回 ${r.date} 的记录</a><article class="article-shell"><div class="card-top">${badges(r)}</div><h1 class="article-title">${e(r.title)}</h1><div class="article-meta"><span>报告时间 ${r.date} ${r.time} 北京时间</span><a href="${e(github(r.path))}" target="_blank" rel="noopener noreferrer">GitHub 原文 ↗</a><a href="${BASE+r.path.split('/').map(encodeURIComponent).join('/')}">Markdown 原文</a></div><div class="caution">${e(r.observation)}<br>这是保留原始来源与判断的历史记录。请以文内观察时点理解数据与风险；不构成投资建议。</div><div class="prose">${markdown(r.markdown,r.path)}</div></article><nav class="article-footer" aria-label="相邻记录">${records[idx+1]?`<a href="${reportHref(records[idx+1].path)}">← 更早：${e(records[idx+1].title)}</a>`:'<span></span>'}${records[idx-1]?`<a href="${reportHref(records[idx-1].path)}">更新：${e(records[idx-1].title)} →</a>`:''}</nav>`;
  const dest=path.join(OUT,r.path.replace(/\.md$/,'.html'));fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,layout(r.title,content));fs.copyFileSync(path.join(ROOT,r.path),path.join(OUT,r.path));
}
const index={schemaVersion:1,timezone:'Asia/Shanghai',repository:'Sakkana/X-feed-pages',recordCount:records.length,records:records.map(({markdown,...r})=>({...r,url:reportHref(r.path),github:github(r.path)}))};
fs.writeFileSync(path.join(OUT,'reports.json'),JSON.stringify(index,null,2)+'\n');
fs.writeFileSync(path.join(ROOT,'reports.json'),JSON.stringify(index,null,2)+'\n');
const table=records.map(r=>`| ${r.date} ${r.time} | ${r.type} | [${r.title}](${r.path.split('/').map(encodeURIComponent).join('/')}) |`).join('\n');
fs.writeFileSync(path.join(ROOT,'README.md'),`# X-feed 研究记录\n\n[打开研究主页](https://sakkana.github.io/X-feed-pages/) · [机器可读索引](reports.json)\n\n按北京时间倒序归档。主页支持日期、主题（含 DeFi、DEX）和关键词筛选，文章保留完整来源、观察时点与风险说明。\n\n研究记录不构成投资建议，历史收益、报价与判断不代表当前情况。\n\n## 研究目录\n\n| 报告时间（北京时间） | 主题 | 报告 |\n| --- | --- | --- |\n${table}\n\n## 更新与发布\n\n1. 将审核过、可以公开的报告加入日期目录。新命名格式为 \`YYYY-MM-DD/HH-MM-SS-【类型】-summary.md\`，现有下划线文件名保持不变\n2. 正文保留原始观察时间、来源链接、成本假设和风险提示。文件名时间为报告发送时间，不替代数据观察时间\n3. 可在 \`metadata.json\` 以完整路径为键补充 \`type\`、\`tags\`、\`summary\`、\`observation\`；文件名中的类型优先\n4. 本地运行 \`node scripts/build.mjs\` 和 \`node scripts/test.mjs\`。生成的 README 和 reports.json 可一并提交\n5. 提交到 main 后，GitHub Actions 自动重新扫描公开 Markdown、生成静态页面并部署 GitHub Pages。线上 reports.json 始终由构建生成\n\n仅日期目录中符合上述新旧格式的 Markdown 会进入网页。站点不需要后端、访问令牌或私有仓库读取权限。\n\n页面源码：\`scripts/\` 与 \`assets/\`；生成目录：\`_site/\`（不提交）。\n`);
fs.writeFileSync(path.join(OUT,'404.html'),layout('没有找到这条记录',`<h1>没有找到这条记录</h1><p>链接可能已变更，请从时间线重新打开。</p><a class="back" href="${BASE}">返回研究时间线</a>`));
fs.writeFileSync(path.join(OUT,'.nojekyll'),'');
console.log(`Built ${records.length} reports (${dates.length} days) into _site`);
